### ISSUE TITLE
parsing array of hashes from params

### ISSUE THREAD

**Issue by rachelhamlin** [rachelhamlin/RESTaurant#2]
I'm trying to parse an array of hashes that are sent through as params with each Order form submitted, in my Orders Controller. The array looks like this:

**[{id:1, name: "mojito", quantity:1}, {id:2, name: "negroni", quantity: 2}]**
(quantity is the attribute being submitted in the form)

I want to use .select to get any item with a quantity greater than 0 and send it to ActiveRecord: 
**order_params[:items].select{|item| item[:quantity] > 0}**

But I can't figure out how to call the params array (order_params[:items]??). 

This is order_params:
**def order_params**

 **params.require(:order).permit(:drinks => [:id, :quantity], :meals => [:id, :quantity], :desserts => [:id, :quantity])**

 **end**

Reading this: http://api.rubyonrails.org/classes/ActionController/Parameters.html

**Comment by CentroDL** [comment]
try this:

``` rb

order_params.collect { |item| item[:quantity] > 0 }

```

did it work?

**Comment by rachelhamlin** [comment]
I updated to: 

`order_params.collect { |item| item[:quantity].to_i > 0 }`

but I'm getting "no implicit conversion of Symbol into Integer"

**Comment by carrafa** [comment]
_met in person_
