### ISSUE TITLE
so close -- updating :quantity attribute with ActiveRecord

### ISSUE THREAD

**Issue by rachelhamlin** [rachelhamlin/RESTaurant#3]
This is so close but it doesn't quite work! I need to be able to add the same menu item to multiple orders, but I get a unique error when I try to do so: 

\\\\\\\\\\\\\\\\\\\
def create
    new_order = order_params[:drinks].select {|item| item[:quantity].to_i > 0}
    Order.create new_order
  end

  private

  def order_params
    params.require(:order).permit(:drinks => [:id, :quantity], :meals => [:id, :quantity], :desserts => [:id, :quantity])
  end

end

////////////////////////////

This is the error:

**PG::UniqueViolation: ERROR: duplicate key value violates unique constraint "orders_pkey" DETAIL: Key (id)=(2) already exists. : INSERT INTO "orders" ("id", "quantity", "created_at", "updated_at") VALUES ($1, $2, $3, $4) RETURNING "id"**

Noooooooo!

Also, I noticed that my database record contains the quantity, but not the party_id or the item_id.

**Comment by carrafa** [comment]
_solved_
